### ISSUE TITLE
split along multiple dimentions

### ISSUE THREAD

**Issue by jkatzs** [bearloga/gsc-utils#5]
Ideally the data we capture is pivotable so that I can see, for instance, how Argentinian traffic on mobile v. desktop is doing over time and filter that by rich results or not.  I understand that that certain combinations are hard because the average changes, but I believe a weighted average can be post-processed using impression data.

**Comment by bearloga** [comment]
Duplicate of #1, fixed in b5596f4cc2eeec983551632ccd7fbaa78e781aab
